FROM reg.mini.dev/python 
EXPOSE 8000
WORKDIR /app 
COPY requirements.txt /app
RUN python3 pip install -r requirements.txt --no-cache-dir
COPY . /app 
ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:8000"]

