name: Build images and push to GAR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: minimus-sa
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/minimus-sa/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Minimus registry auth"
        run: docker login -u minimus -p ${{ secrets.MINIMUS_TOKEN }} reg.mini.dev

      - name: "GAR auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build python image
        run: podman build -t ${{ env.GAR_LOCATION }}python/python-library:latest .

      - name: Build python-mini image
        run: podman build -t ${{ env.GAR_LOCATION }}python/python-mini:latest -f Dockerfile.mini .      
        

      - name: Push python image
        run: podman push ${{ env.GAR_LOCATION }}python/python-library:latest

      - name: Push python-mini image
        run: podman push ${{ env.GAR_LOCATION }}python/python-mini:latest
